version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: mongo-url-shortener
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always
  redis:
    image: redis
    container_name: redis-url-shortener
    ports:
      - "6379:6379"
    restart: always

volumes:
  mongo-data: